apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
# data:
#   DB_HOST: postgresql.postgresql.svc.cluster.local
#   DB_PORT: 5432
#   DB_NAME: bGFiMg==
#   DB_USER: cG9zdGdyZXM=
#   DB_PASSWORD: cG9zdGdyZXM=
#   REDIS_URL: redis.redis.svc.cluster.local
#   REDIS_PASSWORD: VHVraTI3Nw==
#   PORT: MzAwMA==
stringData:
  DB_HOST: postgresql.postgresql.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: lab2
  DB_USER: postgres
  DB_PASSWORD: matkhau123
  REDIS_URL: redis://redis-master.redis.svc.cluster.local:6379
  REDIS_PASSWORD: matkhau123
  PORT: "3000"
